-- MySQL Script generated by MySQL Workbench
-- dom 12 abr 2020 13:11:29 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PTA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PTA` ;

-- -----------------------------------------------------
-- Schema PTA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PTA` DEFAULT CHARACTER SET utf8 ;
USE `PTA` ;

-- -----------------------------------------------------
-- Table `PTA`.`Taldeak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA`.`Taldeak` ;

CREATE TABLE IF NOT EXISTS `PTA`.`Taldeak` (
  `izena` VARCHAR(45) NOT NULL,
  `deskribapena` VARCHAR(1000) NOT NULL,
  `herrialdea` VARCHAR(45) NOT NULL,
  `musika mota` VARCHAR(45) NOT NULL,
  `bakarkakoa` TINYINT(1) NOT NULL,
  `webOrria` VARCHAR(150) NULL,
  `pasahitza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`izena`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA`.`TaldePartaideak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA`.`TaldePartaideak` ;

CREATE TABLE IF NOT EXISTS `PTA`.`TaldePartaideak` (
  `username` VARCHAR(45) NOT NULL,
  `jaiotze data` DATE NOT NULL,
  `herrialdea` VARCHAR(20) NOT NULL,
  `taldeRola` VARCHAR(45) NOT NULL,
  `fk_Taldeak_izena` VARCHAR(45) NOT NULL,
  INDEX `fk_TaldePartaideak_Taldeak1_idx` (`fk_Taldeak_izena` ASC),
  PRIMARY KEY (`username`),
  CONSTRAINT `fk_TaldePartaideak_Taldeak1`
    FOREIGN KEY (`fk_Taldeak_izena`)
    REFERENCES `PTA`.`Taldeak` (`izena`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA`.`Erabiltzaileak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA`.`Erabiltzaileak` ;

CREATE TABLE IF NOT EXISTS `PTA`.`Erabiltzaileak` (
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `izena` VARCHAR(45) NOT NULL,
  `abizena` VARCHAR(45) NOT NULL,
  `deskribapena` VARCHAR(45) NULL,
  `taldePartaide` TINYINT(1) NOT NULL,
  `fk_TaldePartaideak_username` VARCHAR(45) NULL,
  PRIMARY KEY (`username`),
  INDEX `fk_Erabiltzaileak_TaldePartaideak1_idx` (`fk_TaldePartaideak_username` ASC),
  CONSTRAINT `fk_Erabiltzaileak_TaldePartaideak1`
    FOREIGN KEY (`fk_TaldePartaideak_username`)
    REFERENCES `PTA`.`TaldePartaideak` (`username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA`.`Kontzertuak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA`.`Kontzertuak` ;

CREATE TABLE IF NOT EXISTS `PTA`.`Kontzertuak` (
  `idKontzertuak` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `lekua` VARCHAR(45) NOT NULL,
  `sarreraPrezioa` FLOAT NOT NULL,
  `sarreraEsteka` VARCHAR(150) NULL,
  `sarreraKop` INT NOT NULL,
  `fk_Taldeak_izena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idKontzertuak`),
  INDEX `fk_Kontzertuak_Taldeak1_idx` (`fk_Taldeak_izena` ASC),
  CONSTRAINT `fk_Kontzertuak_Taldeak1`
    FOREIGN KEY (`fk_Taldeak_izena`)
    REFERENCES `PTA`.`Taldeak` (`izena`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PTA`.`Gustokoenak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PTA`.`Gustokoenak` ;

CREATE TABLE IF NOT EXISTS `PTA`.`Gustokoenak` (
  `idGustokoenak` INT NOT NULL AUTO_INCREMENT,
  `fk_Erabiltzaileak_username` VARCHAR(45) NOT NULL,
  `fk_Taldeak_izena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGustokoenak`),
  INDEX `fk_Gustokoenak_Erabiltzaileak1_idx` (`fk_Erabiltzaileak_username` ASC),
  INDEX `fk_Gustokoenak_Taldeak1_idx` (`fk_Taldeak_izena` ASC),
  CONSTRAINT `fk_Gustokoenak_Erabiltzaileak1`
    FOREIGN KEY (`fk_Erabiltzaileak_username`)
    REFERENCES `PTA`.`Erabiltzaileak` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gustokoenak_Taldeak1`
    FOREIGN KEY (`fk_Taldeak_izena`)
    REFERENCES `PTA`.`Taldeak` (`izena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
